export const resObj = {
  kind: "customsearch#search",
  url: {
    type: "application/json",
    template:
      "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
  },
  queries: {
    request: [
      {
        title: "Google Custom Search - hello",
        totalResults: "72830000000",
        searchTerms: "hello",
        count: 10,
        startIndex: 1,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "a446a7505cee44d0a",
        searchType: "image",
      },
    ],
    nextPage: [
      {
        title: "Google Custom Search - hello",
        totalResults: "72830000000",
        searchTerms: "hello",
        count: 10,
        startIndex: 11,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "a446a7505cee44d0a",
        searchType: "image",
      },
    ],
  },
  context: {
    title: "go-clone",
  },
  searchInformation: {
    searchTime: 0.303911,
    formattedSearchTime: "0.30",
    totalResults: "72830000000",
    formattedTotalResults: "72,830,000,000",
  },
  items: [
    {
      kind: "customsearch#result",
      title: "hello 2.0 — Basic Apple Guy",
      htmlTitle: "<b>hello</b> 2.0 — Basic Apple Guy",
      link: "https://basicappleguy.com/s/HelloLight_Mac.png",
      displayLink: "basicappleguy.com",
      snippet: "hello 2.0 — Basic Apple Guy",
      htmlSnippet: "<b>hello</b> 2.0 — Basic Apple Guy",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://basicappleguy.com/basicappleblog/hello-20",
        height: 3384,
        width: 6016,
        byteSize: 348914,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTTSo_s8vvElGgzXn-WwucdTCy-JipvIJaUy6V2DEKoqcglzhUaDIhxA&s",
        thumbnailHeight: 84,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Hello! | Super Simple Songs - YouTube",
      htmlTitle: "<b>Hello</b>! | Super Simple Songs - YouTube",
      link: "https://i.ytimg.com/vi/tVlcKp3bWH8/maxresdefault.jpg",
      displayLink: "www.youtube.com",
      snippet: "Hello! | Super Simple Songs - YouTube",
      htmlSnippet: "<b>Hello</b>! | Super Simple Songs - YouTube",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://www.youtube.com/watch?v=tVlcKp3bWH8",
        height: 720,
        width: 1280,
        byteSize: 135861,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlKXSn3G5-Z0o65o-KSE7hNmVEUmPevQ3vg8zrVVOU8TfOb8sfJPlXtfA&s",
        thumbnailHeight: 84,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Sanrio Friend of the Month: Hello Kitty",
      htmlTitle: "Sanrio Friend of the Month: <b>Hello</b> Kitty",
      link: "https://cdn.shopify.com/s/files/1/0416/8083/0620/files/01132022_soc_pinterestboardcoverupdate_HK02_1200x1200_8e0362aa-6b38-4f53-9d87-227bc923075d_1024x1024.png?v=1667247735",
      displayLink: "www.sanrio.com",
      snippet: "Sanrio Friend of the Month: Hello Kitty",
      htmlSnippet: "Sanrio Friend of the Month: <b>Hello</b> Kitty",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink:
          "https://www.sanrio.com/blogs/sanrio/sanrio-friend-of-the-month-hello-kitty-1",
        height: 1024,
        width: 1024,
        byteSize: 256658,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrs1hWu4tj_ojC2yJLl9q-f5WXNYikRykJ-53PrOivLj1i13r64NjthaP8&s",
        thumbnailHeight: 150,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Hello Kitty (@hellokitty) / Twitter",
      htmlTitle: "<b>Hello</b> Kitty (@hellokitty) / Twitter",
      link: "https://pbs.twimg.com/profile_images/1609597504877907969/t3nHKvHd_400x400.jpg",
      displayLink: "twitter.com",
      snippet: "Hello Kitty (@hellokitty) / Twitter",
      htmlSnippet: "<b>Hello</b> Kitty (@hellokitty) / Twitter",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://twitter.com/hellokitty",
        height: 400,
        width: 400,
        byteSize: 12706,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-KZJoC2C0J67d-7fLWwdjtRx36ChXf6VbD7gZrwScROiCZbaI_Q15&s",
        thumbnailHeight: 124,
        thumbnailWidth: 124,
      },
    },
    {
      kind: "customsearch#result",
      title: "Apple Hello Lettering Animation | Figma Community",
      htmlTitle: "Apple <b>Hello</b> Lettering Animation | Figma Community",
      link: "https://s3-alpha.figma.com/hub/file/1407877333/b958324e-d526-4e83-a4c9-abe02c4ea3a6-cover.png",
      displayLink: "www.figma.com",
      snippet: "Apple Hello Lettering Animation | Figma Community",
      htmlSnippet: "Apple <b>Hello</b> Lettering Animation | Figma Community",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://www.figma.com/community/file/1055787798072665276",
        height: 960,
        width: 1707,
        byteSize: 138037,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr-XpQe_ep-pVCr6Rid6d2GN-c2wcypBkbyyEuL55qwctVy2KsGkixgQ&s",
        thumbnailHeight: 84,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "HELLO!",
      htmlTitle: "<b>HELLO</b>!",
      link: "https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=89982930077",
      displayLink: "www.facebook.com",
      snippet: "HELLO!",
      htmlSnippet: "<b>HELLO</b>!",
      mime: "image/",
      fileFormat: "image/",
      image: {
        contextLink: "https://www.facebook.com/hello/",
        height: 464,
        width: 464,
        byteSize: 4784,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKybZTrHRJvJ_BdlzT3zp9n6emA3KoqnOyIZHkElznnKES2nNw_yqv-hE&s",
        thumbnailHeight: 128,
        thumbnailWidth: 128,
      },
    },
    {
      kind: "customsearch#result",
      title: "Hello, Dolly! (1969) - IMDb",
      htmlTitle: "<b>Hello</b>, Dolly! (1969) - IMDb",
      link: "https://m.media-amazon.com/images/M/MV5BODJmZmFiNzQtMDJiYS00ZTgzLTljZGMtNjEzNzM4NmEyYjNiXkEyXkFqcGdeQXVyNjE5MjUyOTM@._V1_.jpg",
      displayLink: "www.imdb.com",
      snippet: "Hello, Dolly! (1969) - IMDb",
      htmlSnippet: "<b>Hello</b>, Dolly! (1969) - IMDb",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://www.imdb.com/title/tt0064418/",
        height: 755,
        width: 497,
        byteSize: 83564,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQegUh_OQ4eK7dc4_0INgGfyWsV5lQA3kKgLdzY56Wp0u8fltXf7Ed3aac&s",
        thumbnailHeight: 142,
        thumbnailWidth: 93,
      },
    },
    {
      kind: "customsearch#result",
      title: "Hello Kitty",
      htmlTitle: "<b>Hello</b> Kitty",
      link: "https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=100044331464480",
      displayLink: "www.facebook.com",
      snippet: "Hello Kitty",
      htmlSnippet: "<b>Hello</b> Kitty",
      mime: "image/",
      fileFormat: "image/",
      image: {
        contextLink: "https://www.facebook.com/hellokitty/",
        height: 1201,
        width: 1201,
        byteSize: 133675,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9_DA5ZiKg7oOETgWbfuMYXhKaBNP9xI4TtU_lCj83VGQup4Ll0uKQHNc&s",
        thumbnailHeight: 150,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Shop Kids – Hello Apparel",
      htmlTitle: "Shop Kids – <b>Hello</b> Apparel",
      link: "http://cdn.shopify.com/s/files/1/1190/4748/t/10/assets/logo.png?v=167108561653742813581641915455",
      displayLink: "www.helloapparelstore.com",
      snippet: "Shop Kids – Hello Apparel",
      htmlSnippet: "Shop Kids – <b>Hello</b> Apparel",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://www.helloapparelstore.com/collections/kids",
        height: 300,
        width: 400,
        byteSize: 11446,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5y_r7Oj7_pTx039mfgkO4Cex5Esu2zHziPkvDBlevVugrO4X62wUn&s",
        thumbnailHeight: 93,
        thumbnailWidth: 124,
      },
    },
    {
      kind: "customsearch#result",
      title: "Hello (TV series) - Wikipedia",
      htmlTitle: "<b>Hello</b> (TV series) - Wikipedia",
      link: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Hello_Web_Series_%28Wordmark%29_Logo.png/1200px-Hello_Web_Series_%28Wordmark%29_Logo.png",
      displayLink: "en.wikipedia.org",
      snippet: "Hello (TV series) - Wikipedia",
      htmlSnippet: "<b>Hello</b> (TV series) - Wikipedia",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://en.wikipedia.org/wiki/Hello_(TV_series)",
        height: 675,
        width: 1200,
        byteSize: 100068,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpLZt4VxvmzrwaO33TTP-bunkhvet55yH6mMivJAvwsiCSxiRL-wWZJDw&s",
        thumbnailHeight: 84,
        thumbnailWidth: 150,
      },
    },
  ],
};
